// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    'nuxt-primevue',
    'nuxt-mongoose',
    "@samk-dev/nuxt-vcalendar",
    "@nuxtjs/supabase"
  ],
  primevue: {
    options: {
        ripple: true,
    },
    components: {
      include: [
        'Button',
        'InputText',
        'DataTable',
        'Column',
        'Dialog',
        'Dropdown',
        'InputNumber',
        'Calendar',
        'InputMask',
        'InputSwitch',
        'InputTextarea',
        'MultiSelect',
        'Password',
        'Rating',
        'Slider',
        'SelectButton',
        'ToggleButton',
        'SelectButton',
        'SplitButton',
        'TabView',
        'TabPanel',
        'Tag',
        'Toast',
        'Toolbar',
        'Tooltip',
        'ProgressSpinner',
        'ProgressBar',
        'Card',
        'Carousel',
        'Chip',
        'Galleria',
        'Avatar',
        'Badge',
        'BlockUI',
        'ScrollPanel',
        'Fieldset',
        'FileUpload',
        'Inplace',
        'InputMask',
        'Knob',
        'OrganizationChart',
        'OverlayPanel',
        'Paginator',
        'Panel',
        'ScrollTop',
        'Skeleton',
        'SpeedDial',
        'Splitter',
        'Sidebar',
        'Tree',
        'TreeTable',
        'Terminal',
        'VirtualScroller',
        'OrderList',
        'PickList',
        'FullCalendar',
        'Timeline',
        'MegaMenu',
        'Stepper',
        'StepperPanel',
        'OrganizationChart',
        'Chart',
        'Dock',
        'Message',
        'Image',
        'Column',
        'ConfirmPopup',
        'Editor',
        'Textarea',
        'FloatLabel',
        'InputGroup',
        'InputGroupAddon'
      ]
    }
  },
  css: ['primevue/resources/themes/aura-light-green/theme.css', 'primeicons/primeicons.css'],
  nitro: {
    plugins: [
      '~/server/mongodb.ts',
      '~/server/createWorkingDaysData.ts',
    ]
  },
  supabase: {
    url: process.env.SUPABASE_URL,
    key: process.env.SUPABASE_KEY
  }
})
